const Router = require("express");
const router = new Router();
const UserController = require("../controllers/usersController");
const authMiddleware = require("../middleware/authMiddleware");
router.post("/registration", UserController.registration);
router.post("/login", UserController.login);
router.get("/auth", authMiddleware, UserController.check);
// router.get("/", UserController.getUserById);
router.get("/", UserController.getUserByEmail);
router.delete("/", UserController.deleteUser);
module.exports = router;
